[CyS](COMPONENTES)(CONEXIONES)(YO*ACREEDORA*):! AUTOMOTOR|INMOBILIARIO
[PLATA](CASA)(OBJETOS)(CAPITAL);! COMPRA-VENTA
[ARTE](EXCLUSIVIDAD)(PREGUNTAS)(MISIONES);! NOVIO
[INFORMACIÓN](AVAL);! SÍMBOLO
[TRANSPORTE](AUTONOMÍA)(CULPABILIDADES Y CASTIGOS)(TRUEQUES);! MOTO CBR.