[CyS](COMPONENTES)(CONEXIONES)(*ACREEDORA*):! AUTOMOTOR|INMOBILIARIO
[PLATA](CASA)(OBJETOS)(CAPITAL);! OBTENCIÓN.
[ARTE](EXCLUSIVIDAD)(PREGUNTAS)(RESPUESTAS);! SÍMBOLO.
[INFORMACIÓN](NOVIO);! AVAL.
[TRANSPORTE](INDEPENDENCIA)(CULPABILIDADES/CASTIGOS)(TRUEQUES);! MOTO CBR.