- Hi! brego por los derechos de los autores.
- 👀 Pioneros de todo el mundo en conflagración.
- 
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
Piki-cpu/Piki-cpu is a ✨ special ✨ repository because its `README.ck` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
---
